//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUITY()
        {
            this.POSITION = new HashSet<POSITION>();
        }
    
        public string Symbol { get; set; }
        public string Name { get; set; }
        public Nullable<int> IPOyear { get; set; }
        public int SectorId { get; set; }
        public int IndustryId { get; set; }
        public string Quote { get; set; }
        public int SecurityId { get; set; }
    
        public virtual INDUSTRY INDUSTRY { get; set; }
        public virtual SECTOR SECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSITION> POSITION { get; set; }
    }
}
