//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioManagerEntity : DbContext
    {
        public PortfolioManagerEntity()
            : base("name=PortfolioManagerEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOND> BOND { get; set; }
        public virtual DbSet<EQUITY> EQUITY { get; set; }
        public virtual DbSet<FUTURE> FUTURE { get; set; }
        public virtual DbSet<INDUSTRY> INDUSTRY { get; set; }
        public virtual DbSet<PORTFOLIO> PORTFOLIO { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<PRICE> PRICE { get; set; }
        public virtual DbSet<SECTOR> SECTOR { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
