//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        public string PositionType { get; set; }
        public int SecurityId { get; set; }
        public int PortfolioId { get; set; }
        public int Quantity { get; set; }
        public int PositionId { get; set; }
    
        public virtual BOND BOND { get; set; }
        public virtual EQUITY EQUITY { get; set; }
        public virtual FUTURE FUTURE { get; set; }
        public virtual PORTFOLIO PORTFOLIO { get; set; }
        public virtual PRICE PRICE { get; set; }
    }
}
