//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE
    {
        public int SecurityId { get; set; }
        public decimal BidPrice { get; set; }
        public decimal OfferPrice { get; set; }
        public System.DateTime Date { get; set; }
        public string SecurityType { get; set; }
    
        public virtual BOND BOND { get; set; }
        public virtual EQUITY EQUITY { get; set; }
        public virtual FUTURE FUTURE { get; set; }
    }
}
